package pe.com.mcco.security.domain.enums;

public enum TipoEvento {
    LOGIN_OK,
    USUARIO_BLOQUEADO,
    USUARIO_BLOQUEADO_INTENTO,
    TOKEN_FIRMA_INVALIDA,
    TOKEN_REVOCADO_INTENTO,
    LOGOUT,
    IDLE_TIMEOUT,
    PASSWORD_CAMBIADO,
    PASSWORD_RESET_SOLICITADO,
    PASSWORD_RESET_OK,
    SESIONES_REVOCADAS_ADMIN,
    REFRESH_INVALIDO
}
