spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  sql:
    init:
      mode: never

app:
  jwt:
    private-key-path: file:${JWT_PRIVATE_KEY_PATH}
    public-key-path: file:${JWT_PUBLIC_KEY_PATH}

server:
  error:
    include-stacktrace: never
    include-message: never

logging:
  level:
    root: INFO
    pe.com.mcco: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
